#!/usr/bin/env bash
# Stamp src/_version.py for a manual `func azure functionapp publish` deploy.
# Run this BEFORE `func publish` so the deploy bundle includes the version metadata.
#
# Usage:
#   ./scripts/stamp_version.sh
#   func azure functionapp publish windowbot-func --python

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "Error: not inside a git repo." >&2
  exit 1
fi

COMMIT_SHA_FULL="$(git rev-parse HEAD)"
COMMIT_SHA="${COMMIT_SHA_FULL:0:7}"
BRANCH="$(git rev-parse --abbrev-ref HEAD)"
COMMIT_TIME="$(git show -s --format=%cI "$COMMIT_SHA_FULL" | python3 -c "import sys; from datetime import datetime, timezone; print(datetime.fromisoformat(sys.stdin.read().strip()).astimezone(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'))")"
BUILD_TIME="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# Derive GitHub URL from origin remote if it points at github.com.
ORIGIN_URL="$(git remote get-url origin 2>/dev/null || echo '')"
COMMIT_URL=""
if [[ "$ORIGIN_URL" == *"github.com"* ]]; then
  # Normalize git@github.com:owner/repo.git → https://github.com/owner/repo
  REPO_PATH="$(echo "$ORIGIN_URL" | sed -E 's|^git@github\.com:|https://github.com/|; s|^https://github\.com/||; s|\.git$||')"
  COMMIT_URL="https://github.com/${REPO_PATH}/commit/${COMMIT_SHA_FULL}"
fi

cat > src/_version.py <<PY
"""Build-stamped version metadata. Generated by scripts/stamp_version.sh — do not edit."""
__commit_sha__ = "${COMMIT_SHA}"
__commit_sha_full__ = "${COMMIT_SHA_FULL}"
__commit_time__ = "${COMMIT_TIME}"
__build_time__ = "${BUILD_TIME}"
__branch__ = "${BRANCH}"
__commit_url__ = "${COMMIT_URL}"
PY

echo "Stamped src/_version.py:"
cat src/_version.py

# Warn if the working tree is dirty — manual deploys of uncommitted changes
# mean the SHA on the status page will not match the deployed code.
if ! git diff --quiet HEAD; then
  echo ""
  echo "WARNING: working tree has uncommitted changes." >&2
  echo "The stamped SHA reflects ${COMMIT_SHA} but the deployed bundle will include local edits." >&2
fi
